### ISSUE TITLE
Provide basic CI

### ISSUE THREAD

**Issue by fabiand** [kubevirt/must-gather#32]
Anoything else to say besides subj?

**Comment by pkliczewski** [comment]
@mmirecki started to work on travis [integration](https://github.com/kubevirt/must-gather/blob/master/.travis.yml). Is there anything you would like to see?

**Comment by fabiand** [comment]
I just think that some basic validation is reasonable as a first step.
It can then always be extended.

**Comment by pkliczewski** [comment]
Are you thinking about validating the output?

**Comment by fabiand** [comment]
There are many things we can do.
I'd start with ensuring that it exits with 0.

Then we can check how it can be extended.

**Comment by pkliczewski** [comment]
I think we can add some tests to the automation. Travis configured in this repo only builds the image.
