### ISSUE TITLE
Check for namespaces existence before collection

### ISSUE THREAD

**Issue by masayag** [kubevirt/must-gather#33]
Certain namespaces exists for OKD/HCO and not for k8s.
A check prior to collection will prevent the failures.

```
Error: namespaces "kubevirt-hyperconverged" not found
Error: namespaces "openshift-operator-lifecycle-manager" not found
Error: namespaces "openshift-marketplace" not found
Error: namespaces "kubemacpool-system" not found
Error: namespaces "linux-bridge" not found
Error: namespaces "openshift-sdn" not found
Error: namespaces "nmstate" not found
Error: namespaces "sriov" not found
Error: namespaces "kubevirt-web-ui" not found
Error: the server doesn't have a resource type "v2vvmwares"
Error: namespaces "cdi" not found
Error: the server doesn't have a resource type "datavolumes"
Error: the server doesn't have a resource type "nodenetworkstates"
Error: the server doesn't have a resource type "istag"
error: the server doesn't have a resource type "templates"
```

**Comment by fromanirh** [comment]
right, but do we care about non-{ocp,okd} setups _for this tool_?

**Comment by pkliczewski** [comment]
must-gather won't work on any other platform. We don't care about anything else

**Comment by masayag** [comment]
> must-gather won't work on any other platform. We don't care about anything else

I did work for k8s cluster (no openshift/hco), just k8s + kubevirt and it collected data for it using the same `oc adm must-gather` as I realized [here](https://github.com/kubevirt/must-gather/issues/28#issuecomment-523884214)

**Comment by alevitter** [comment]
How would a check before collection be any better than trying and failing immediately when `openshift-must-gather inspect` detects that the resource isn't there? It seems like the difference is between `Error: namespaces "kubevirt-hyperconverged" not found` and `Skipping namespace "kubevirt-hyperconverged"; namespace not found`

This only would be better if the must-gather took a while to detect that a namespace isn't there, which doesn't seem to be the case.

And to actually check would basically do the same thing as the error- you're querying the cluster for the existence of the resource and seeing if it returns that it exists or not.

The only feasible difference is if, in the case that the resources aren't found, we don't want the script to say anything at all, which considering the purpose of the tool does not seem to be correct.

**Comment by pkliczewski** [comment]
Having information that specific namespace is not there is meaningful. The difference would be how we present this information to the user as you specified in the comment above.

**Comment by masayag** [comment]
that makes better sense, I'm closing this issue and #38 will be used to differentiate between the cluster types.
